// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var SampleCombine = require("xstream/extra/sampleCombine");

function sampleCombine(combined, source) {
  return SampleCombine.default(combined)(source);
}

exports.sampleCombine = sampleCombine;
/* xstream/extra/sampleCombine Not a pure module */
