// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Xstream = require("xstream");

function fromList(l, xs) {
  return xs.fromArray($$Array.of_list(l));
}

var interval = Xstream.default.periodic(1000);

interval.map((function (i) {
          return String(i + 1 | 0) + " seconds passed";
        })).subscribe({
      next: (function (value) {
          console.log(value);
          return /* () */0;
        })
    });

exports.fromList = fromList;
exports.interval = interval;
/* interval Not a pure module */
